#!/bin/bash


VERSION=8.0.25
SRC_DIR=binary-source
SOURCE_NAME="adman_gtk-${VERSION}"

rm -rf "${SOURCE_NAME}"

mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
mkdir "${SOURCE_NAME}"

mkdir -p "${SOURCE_NAME}/opt/adman"
mkdir -p "${SOURCE_NAME}/usr/bin"
mkdir -p "${SOURCE_NAME}/usr/share/applications"

cp -r "${SRC_DIR}/." "${SOURCE_NAME}/opt/adman"

touch "${SOURCE_NAME}/opt/adman/adm-app.desktop"
touch "${SOURCE_NAME}/usr/bin/adman"

cat <<EOF > "${SOURCE_NAME}/opt/adman/adm-app.desktop"
[Desktop Entry]
Version=1.0
Encoding=UTF-8
Exec=env GTK_USE_PORTAL=1 /opt/adman/adm-app %U
Type=Application
Terminal=false
Name=Axioos Download Manager
Comment=Axioos Download Manager
Categories=Network;
Icon=/opt/adman/adm-logo.svg
MimeType=application/adm-app;x-scheme-handler/adm-app;
StartupNotify=true
EOF

cat <<EOF > "${SOURCE_NAME}/usr/bin/adman"
#!/bin/bash
export GTK_USE_PORTAL=1 
/opt/adman/adm-app \$@
EOF

cat <<EOF > "${SOURCE_NAME}/opt/adman/source_pkg"
adman_gtk|.rpm
EOF

cp "${SOURCE_NAME}/opt/adman/adm-app.desktop" "${SOURCE_NAME}/usr/share/applications"

chmod 755 "${SOURCE_NAME}/usr/bin/adman"
chmod 755 "${SOURCE_NAME}/opt/adman/adm-app"

tar --create --file "${SOURCE_NAME}.tar.gz" "${SOURCE_NAME}"
mv "${SOURCE_NAME}.tar.gz" "rpmbuild/SOURCES"

cat <<EOF > "rpmbuild/SPECS/adman_gtk.spec"
Name:       	adman_gtk
Version:    	${VERSION}
Release:    	1%{?dist}
Summary:    	Axioos Download Manager
AutoReqProv: 	no
Requires:   	gtk3 >= 3.22
Requires:   	(ffmpeg-free or ffmpeg)

Group:      	System Environment/Base
License:    	GPLv3+
Source0:    	${SOURCE_NAME}.tar.gz

%description
Open source download accelerator and video downloader.

%prep
%setup -q

%install
cp -rfa * %{buildroot}

%files
/usr/bin/*
/usr/share/applications/*
/opt/adman/*
EOF

rpmbuild --define "_topdir `pwd`/rpmbuild" -bb rpmbuild/SPECS/adman_gtk.spec