name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
    - name: Setup .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore ADM/ADM.Wpf.UI/ADM.Wpf.UI.csproj -p:Platform=x86
    - name: Build
      run: dotnet build ADM/ADM.Wpf.UI/ADM.Wpf.UI.csproj --no-restore -c Release -f net4.7.2 -p:Platform=x86 -p:UseSharedCompilation=false
